### ISSUE TITLE
Marketplace AMI terminate / Stop Error

### ISSUE THREAD

**Issue by aaravindanarun** [jtriley/StarCluster#255] opened 2013-06-04 11:51 UTC
$ starcluster terminate mycluster

Try to terminate instance using starcluster command,
I got error message,

```
    Detaching volume vol-c63d77cf from master
    !!! ERROR - IncorrectInstanceState: Unable to detach volume 'vol-c63d77cf' with Marketplace codes from instance 'i-e18dffb6' as the instance is not in the 'stopped' state.
```

**Comment by jtriley** [comment] 2013-06-21 19:00
Another duplicate of #238. _Please_ stop duplicating issue reports.

**Closed as completed by jtriley** 2013-06-21 19:00 UTC
