### ISSUE TITLE
Thread error at end of starting cluster

### ISSUE THREAD

**Issue by JohnCEarls** [jtriley/StarCluster#135] opened 2012-08-03 18:26 UTC
Hi,

Starcluster is great, btw.

I'm running off the dev branch and I receive the following error after the cluster is started:

---

Exception in thread Thread-21 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/local/lib/python2.6/dist-packages/ssh-1.7.14-py2.6.egg/ssh/transport.py", line 1602, in runI 
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

---

Happens right after "This will start all 'stopped' nodes and reconfigure the cluster." is displayed

I checked the debug.log and the error was not logged.  This appears to be happening on exit.

Definitely not a show stopper.  

Running this on Ubuntu 10.04, python 2.6, m1-large spot instances, I have a plugin that ssh's and pip installs sk-learn, but this was not happening when I was running on the dev branch.

Again, great software.  Love using it.

**Comment by jtriley** [comment] 2012-08-03 19:09
@JohnCEarls I've seen this error before but very rarely. This is ultimately a threading issue with Python 'ssh' (formerly paramiko) where its threads are still running when the interpreter is shutting down. As you discovered this isn't a fatal error but annoying none the less. Finding a fix for this is difficult given that it's a transient error and hard to reproduce (at least for me anyway...). There's an issue for this in the Python 'ssh' issue tracker:

bitprophet/ssh#28

**Comment by jtriley** [comment] 2012-09-18 17:01
@JohnCEarls Looks like @bitprophet has a fix coming for this (see bitprophet/ssh#28) and should be included in the next release of the Python 'ssh' library. I will close this issue when the next version gets released.

**Closed as completed** 2012-12-29 01:44 UTC

**Comment by jtriley** [comment] 2012-12-29 01:48
The above commit is an attempt to fix this by registering all SSHClient object's close() methods to be called on interpreter shutdown using the 'atexit' module. Please reopen if you encounter the issue again.
