### ISSUE TITLE
Error when running removenode

### ISSUE THREAD

**Issue by daviderickson** [jtriley/StarCluster#120] opened 2012-07-12 22:35 UTC
Here is the log:
$ starcluster removenode c node001 node002
StarCluster - (http://web.mit.edu/starcluster) (v. 0.93.3)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

> > > Removing node node001 (i-e4d2419c)...
> > > Removing node001 from known_hosts files
> > > Removing node001 from /etc/hosts
> > > Removing node001 from NFS
> > > Removing node001 from SGE
> > > !!! ERROR - command 'source /etc/profile && qconf -dconf node001' failed with status 1
> > > Updating SGE parallel environment 'orte'
> > > 2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > Adding parallel environment 'orte' to queue 'all.q'
> > > Removing node node001 (i-e4d2419c)...
> > > Removing node001 from known_hosts files
> > > Removing node001 from /etc/hosts
> > > Removing node001 from NFS
> > > Terminating node: node001 (i-e4d2419c)

**Comment by jtriley** [comment] 2012-07-24 13:36
@daviderickson Would you mind finding this error in your $HOME/.starcluster/logs/debug.log file and pasting the surrounding lines here? That should give more details on what the issue is. I need to update sshutils to dump the output whenever there's an error...

**Comment by daviderickson** [comment] 2012-08-03 07:17
Here you go, sorry for the delay:

```
2012-08-03 03:15:29,258 PID: 3951 clustersetup.py:377 - INFO - Removing node002 from /etc/hosts
2012-08-03 03:15:29,324 PID: 3951 __init__.py:284 - DEBUG - new /etc/hosts after removing regex (node002) matches:
127.0.0.1 ubuntu

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
# Added by cloud-init
127.0.1.1   ip-10-4-83-9.ec2.internal ip-10-4-83-9
10.4.83.9 master

2012-08-03 03:15:29,552 PID: 3951 clustersetup.py:379 - INFO - Removing node002 from NFS
2012-08-03 03:15:29,617 PID: 3951 __init__.py:284 - DEBUG - new /etc/exports after removing regex (node002) matches:
# /etc/exports: the access control list for filesystems which may be exported
#       to NFS clients.  See exports(5).
#
# Example for NFSv2 and NFSv3:
# /srv/homes       hostname1(rw,sync,no_subtree_check) hostname2(ro,sync,no_subtree_check)
#
# Example for NFSv4:
# /srv/nfs4        gss/krb5i(rw,sync,fsid=0,crossmnt,no_subtree_check)
# /srv/nfs4/homes  gss/krb5i(rw,sync,no_subtree_check)
#

2012-08-03 03:15:29,869 PID: 3951 __init__.py:543 - DEBUG - exportfs: scandir /etc/exports.d: No such file or directory
2012-08-03 03:15:29,869 PID: 3951 __init__.py:543 - DEBUG - 
2012-08-03 03:15:29,964 PID: 3951 cluster.py:664 - DEBUG - existing nodes: {u'i-7123e50a': <Node: node002 (i-7123e50a)>, u'i-c25823ba': <Node: master (i-c25823ba)>}
2012-08-03 03:15:29,964 PID: 3951 cluster.py:667 - DEBUG - updating existing node i-c25823ba in self._nodes
2012-08-03 03:15:29,964 PID: 3951 cluster.py:667 - DEBUG - updating existing node i-7123e50a in self._nodes
2012-08-03 03:15:29,964 PID: 3951 cluster.py:680 - DEBUG - returning self._nodes = [<Node: master (i-c25823ba)>, <Node: node002 (i-7123e50a)>]
2012-08-03 03:15:29,964 PID: 3951 sge.py:161 - INFO - Removing node002 from SGE
2012-08-03 03:15:30,029 PID: 3951 __init__.py:543 - DEBUG - root@master modified "@allhosts" in host group list 
2012-08-03 03:15:30,164 PID: 3951 __init__.py:543 - DEBUG - root@master modified "all.q" in cluster queue list 
2012-08-03 03:15:30,375 PID: 3951 __init__.py:538 - ERROR - command 'source /etc/profile && qconf -dconf node002' failed with status 1
2012-08-03 03:15:30,375 PID: 3951 __init__.py:543 - DEBUG - can't resolve hostname "node002"
2012-08-03 03:15:30,375 PID: 3951 __init__.py:543 - DEBUG - root@master removed "node002" from configuration list 
2012-08-03 03:15:30,507 PID: 3951 __init__.py:543 - DEBUG - root@master removed "node002" from execution host list 
```

**Comment by jtriley** [comment] 2013-01-03 19:40
@daviderickson My apologies for losing track of this. Are you able to reproduce this issue? Judging by your logs the default plugin's on_remove_node is being executed before the SGE plugin for some reason. This causes the node to be removed from /etc/hosts, NFS, etc. before SGE attempts to remove the node and by that time the hostname 'node002' cannot be resolved (because it was removed).

In any event, I've just tested removenode with latest git code (soon to be 0.94) and it seems to work so I'm going to close this now. Please feel free to reopen if you're still having this issue or experience it after next release. Thanks!

**Closed as completed by jtriley** 2013-01-03 19:40 UTC

**Comment by jtriley** [comment] 2013-01-03 19:46
@daviderickson FWIW I just now tried your removenode command with a 3-node cluster and it worked without errors: 
i.e:

```
$ starcluster removenode mycluster node001 node002
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

>>> Running plugin starcluster.plugins.ipcluster.IPCluster
>>> Running plugin starcluster.plugins.sge.SGEPlugin
>>> Removing node001 from SGE
>>> Updating SGE parallel environment 'orte'
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
>>> Adding parallel environment 'orte' to queue 'all.q'
>>> Running plugin starcluster.clustersetup.DefaultClusterSetup
>>> Removing node node001 (i-81ea3bf0)...
>>> Removing node001 from known_hosts files
>>> Removing node001 from /etc/hosts
>>> Removing node001 from NFS
>>> Running plugin starcluster.plugins.ipcluster.IPCluster
>>> Running plugin starcluster.plugins.sge.SGEPlugin
>>> Removing node002 from SGE
>>> Updating SGE parallel environment 'orte'
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
>>> Adding parallel environment 'orte' to queue 'all.q'
>>> Running plugin starcluster.clustersetup.DefaultClusterSetup
>>> Removing node node002 (i-9fea3bee)...
>>> Removing node002 from known_hosts files
>>> Removing node002 from /etc/hosts
>>> Removing node002 from NFS
```
