### ISSUE TITLE
runplugin fails if already logged into node

### ISSUE THREAD

**Issue by jvimal** [jtriley/StarCluster#93] opened 2012-03-16 16:25 UTC
If I am already logged into a node, runplugin fails with the following error.  Otherwise, it runs successfully.

```
StarCluster - (http://web.mit.edu/starcluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

!!! ERROR - Remote SSH access for user 'root' denied via authorized_keys
!!! ERROR - 
!!! ERROR - This usually means the AMI you're using has been configured
!!! ERROR - to deny SSH access for the 'root' user. Either fix your AMI
!!! ERROR - or use one of the StarCluster supported AMIs. You can obtain
!!! ERROR - a list of StarCluster supported AMIs using the 'listpublic'
!!! ERROR - command:
!!! ERROR - 
!!! ERROR -     $ starcluster listpublic
!!! ERROR - 
!!! ERROR - If you need to customize one of the StarCluster supported
!!! ERROR - AMIs simply launch an instance of the AMI, login remotely,
!!! ERROR - configure the instance, and then use the 'ebsimage' command
!!! ERROR - to create a new EBS AMI from the instance with your changes:
!!! ERROR - 
!!! ERROR -     $ starcluster ebsimage <instance-id> <image-name>
!!! ERROR - 
!!! ERROR - Pass the --help flag to the 'ebsimage' command for more
!!! ERROR - details.
```

**Comment by jtriley** [comment] 2012-03-16 17:35
Sorry I'm not following you. What do you mean exactly by already logged into a node? Also can you please share the exact command you're using? As the error says this usually happens when you're using an AMI that does not permit root logins. What AMI are you using?

**Comment by jvimal** [comment] 2012-03-16 18:11
Here is the sequence of steps to reproduce the above issue.   I am using ami-c6bd30f6 on m1.small instance.
1. Start a cluster using default template:  starcluster start -s 4 cluster
2. Login to master node: starcluster sn cluster master
3. Create a plugin that runs a command (say ls) on all nodes.  (The standard example would do.)
4. Run the plugin: starcluster rp plugin cluster

In the above sequence, step 4 would result in an error.   However, if you omit step 2, in the sequence, but follow steps 1, 3 and 4, step 4 would work as expected.

**Comment by jtriley** [comment] 2012-03-16 18:48
Your steps above work no problem for me as they should. Are you able to _consistently_ reproduce this? Try just running steps 2 and 4 over and over on the same cluster. Does it happen every single time? Also, what is your plugin doing?

This error is only ever raised when a "garbage packet" is received when trying to connect to the instance over SSH/SFTP which almost always occurs because of cloudinit not permitting root login by an authorized_keys hack. 

I suppose this could just be a bad connection issue in which case the error should be reworded a bit to include the fact that it might be the AMI or faulty network connection.

**Comment by jvimal** [comment] 2012-03-17 02:00
Yes, it happens every time.  The plugin iterates over all nodes and executes install commands:

``` python
   def run(self, nodes, master, user, user_shell, volumes):
          for node in nodes:
            node.ssh.execute('apt-get update; <more commands>')
```

**Comment by jtriley** [comment] 2012-03-17 02:53
Hmmm this is bizarre given that the sshmaster and sshnode commands are very simple and do nothing more than look up the instance's public dns name and call your openssh client to login to the nodes. 

Please pull the latest code and try this again. I updated the code to log any "garbage packet received" exceptions raised to the debug log. Once you're able to reproduce with the latest github code check ~/.starcluster/logs/debug.log for the "garbage packet received" exception and paste here.

**Comment by jtriley** [comment] 2012-07-17 21:54
@jvimal I would double check your node.ssh.execute command especially the "more commands" part because I suspect it, perhaps unknowingly, modifies root's ~/.ssh/authorized_keys file and adds an "echo" command to the beginning of the first line in authorized_keys. 

You can test this easily:
1. Start a cluster without the plugin running at start-up
2. Login using sshmaster command
3. Run cat ~/.ssh/authorized_keys and verify the line doesn't start with "echo".
4. While still logged into the master, run your plugin with the runplugin command and check whether 'echo' gets added 
   to root's authorized_keys file. 

If, in fact, your plugin run does cause root's ~/.ssh/authorized_keys file to be updated with an echo statement then this is not a bug in StarCluster but an issue with the command line you're using in node.ssh.execute. You can test this yourself by replacing your node.ssh.execute command with something simple like 'ls' and then verifying the problem goes away.

I suspect this is the case so I'm closing this issue now. If you investigate this further and still feel it's a StarCluster bug please feel free to re-open the bug.

**Closed as completed by jtriley** 2012-07-17 21:54 UTC
Labels: Investigate
