### ISSUE TITLE
Added nodes end up in incorrect availability zone 0.94.2 only using spot

### ISSUE THREAD

**Issue by johnbot1** [jtriley/StarCluster#312] opened 2013-10-22 21:29 UTC
After configuring a fixed availability zone in the Starcluster config file (us-west-2b for example), I can now launch a _non-spot_ cluster with many nodes and they all end up in us-west-2b as expected. I can also add non-spot nodes after the fact and they get provisioned properly in us-west-2b and startup fine. 

However, if I create a new spot enabled cluster (in us-west-2b) I can add a bunch of spot enabled nodes during launch with no problem but if I add additional spot nodes after the fact they all end up in us-west-2c and not in us-west-2b causing a failure in AWS to provision the spot instances and the AWS Status Message: Your Availability Zone Group is spread across multiple Availability Zones and Constraint-not-fullfillable.

I should add that adding spot nodes to a cluster in us-west-2a after the fact also causes all additional spot nodes to end up in us-west-2c so somehow the logic is defaulting to that it seems. My region is defaulted to VPC and does not use classic.

I would really like to get spot working since I plan on provisioning cc2.8xlarge nodes entirely and at 2.40/hour non-spot would get horrifically expensive fast......

**Comment by schmutze** [comment] 2013-10-23 16:10
I'm fairly certain this is due to "availability zone groups" not being relevant in VPC.

@jtriley - is it possible to change the add node strategy to use the availability zone defined in the config file instead of relying on availability zone groups? I think eliminating the use of availability zone groups and always using the defined availability zone would be a safe change for both "ec2 classic" and "vpc only" users. Of course if the user does not define an availability zone then you could either use the logic in the code to determine which zone the cluster landed in upon initial startup, or the additional node would land in a random zone (not ideal for performance but still better than resulting in vague AWS errors that might not make sense to the user).

Does any of this make sense?

thanks,
chad

**Comment by jtriley** [comment] 2013-11-12 18:20
OK I think I've figured out where a lot of this is coming from. It turns out that merging #236 caused some regressions for addnode. Working on a bunch of fixes now.

**Comment by schmutze** [comment] 2013-11-12 19:38
Thanks! Let me know how I can help.

**Closed as completed** 2013-11-14 17:01 UTC
