### ISSUE TITLE
Creating 2nd cluster breaks passwordless ssh on 1st cluster

### ISSUE THREAD

**Issue by jbheman** [jtriley/StarCluster#99] opened 2012-03-29 23:31 UTC
when i create a 2nd cluster I can no longer sshmaster to the 1st cluster as user sgeadmin. root can ssh. 

to allow sgeadmin to login I have to login as root and create a password for sgeadmin. then you can ssh, but with a password.

**Comment by jtriley** [comment] 2013-01-04 17:15
@jbheman My apologies for losing track of this. I'm not able to reproduce this so I'm going to close the issue. It might be possible that you're unknowingly using different usernames for each cluster. Please reopen if you're still having this issue.

**Closed as completed by jtriley** 2013-01-04 17:15 UTC
