### ISSUE TITLE
Node alias + addnode problem

### ISSUE THREAD

**Issue by dpolhamus** [jtriley/StarCluster#338] opened 2013-11-26 16:16 UTC
In both the stable release and developmental version, there is a problem with creating the node aliases that is preventing addition of more than one node at a time.  To see the problem, try starting a cluster of size 3 or more.  Alternatively, start a single node cluster and add two nodes.  EC2 "userdata" in nodes contains junk as of 11/25/13, I suspect this is related.
Python 2.7.5, Mac OS/X Mavericks

**Comment by jriehl** [comment] 2013-11-26 21:35
So, is the following related?

```
Traceback (most recent call last):
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/commands/start.py", line 215, in execute
    validate_running=validate_running)
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/cluster.py", line 1485, in start
    return self._start(create=create, create_only=create_only)
  File "<string>", line 2, in _start
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/utils.py", line 111, in wrap_f
    res = func(*arg, **kargs)
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/cluster.py", line 1508, in _start
    self.setup_cluster()
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/cluster.py", line 1516, in setup_cluster
    self.wait_for_cluster()
  File "<string>", line 2, in wait_for_cluster
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/utils.py", line 111, in wrap_f
    res = func(*arg, **kargs)
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/cluster.py", line 1301, in wait_for_cluster
    self.wait_for_running_instances()
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/cluster.py", line 1256, in wait_for_running_instances
    nodes = nodes or self.get_nodes_or_raise()
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/cluster.py", line 731, in get_nodes_or_raise
    nodes = self.nodes
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/cluster.py", line 721, in nodes
    if n.is_master():
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/node.py", line 884, in is_master
    return self.alias == "master"
  File "/home/jriehl/.virtualenvs/tcg/local/lib/python2.7/site-packages/starcluster/node.py", line 140, in alias
    aliases = aliasestxt.splitlines()[2:]
 AttributeError: 'NoneType' object has no attribute 'splitlines'
```

I sent an email to the StarCluster mailing list last night where I characterized this as a possible race condition.  When I hit this exception, the nodeXXX instances are running, but according to the EC2 console the "Name" tag isn't set, and the user data is empty.

**Comment by dpolhamus** [comment] 2013-11-26 21:38
Yes,  I believe this is the same issue.
Dan

**Comment by jtriley** [comment] 2013-12-03 21:21
@drexell0680 Intersting, I'm not able to reproduce this issue either by starting a 5 node cluster or a single node cluster and adding nodes (both of which I do _all_ the time). Can you reliably reproduce this? If so I'm curious whether waiting a few minutes and then running `starcluster start -x yourcluster` fixes it or not. Also, _please_ include the original crash report if it's available - it contains useful version information and most importantly the original traceback. 

@jriehl This does seem like a race-condition. If it is then the `starcluster start -x yourcluster` test above will tell us. In general StarCluster uses (part) of the userdata to store instance names so that it can 'pin' a name to the instance even before it comes up or even exists (e.g. spot request). StarCluster tries repeatedly to fetch the user data until it succeeds. So if this is a race-condition then perhaps the EC2 API is returning a blank user_data for some time until it's available....

**Comment by dpolhamus** [comment] 2013-12-03 21:25
@justin This is looking like an error on AWS's end.  As of yesterday
morning, these issues are gone for me but they did persist through last
week.  You can close this "bug", which apparently was never a StarCluster
bug anyway.

On Tue, Dec 3, 2013 at 4:21 PM, Justin Riley notifications@github.comwrote:

> @drexell0680 https://github.com/drexell0680 Intersting, I'm not able to
> reproduce this issue either by starting a 5 node cluster or a single node
> cluster and adding nodes (both of which I do _all_ the time). Can you
> reliably reproduce this? If so I'm curious whether waiting a few minutes
> and then running starcluster start -x yourcluster fixes it or not. Also,
> _please_ include the original crash report if it's available - it
> contains useful version information and most importantly the original
> traceback.
> 
> @jriehl https://github.com/jriehl This does seem like a race-condition.
> If it is then the starcluster start -x yourcluster test above will tell
> us. In general StarCluster uses (part) of the userdata to store instance
> names so that it can 'pin' a name to the instance even before it comes up
> or even exists (e.g. spot request). StarCluster tries repeatedly to fetch
> the user data until it succeeds. So if this is a race-condition then
> perhaps the EC2 API is returning a blank user_data for some time until it's
> available....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jtriley/StarCluster/issues/338#issuecomment-29752614
> .

## 

Daniel G Polhamus, PhD
Metrum Research Group, LLC
2 Tunxis Rd, Suite 112
Tariffville, CT 06081
(888) 308-7049 ext 403

**Comment by jtriley** [comment] 2013-12-03 21:27
@drexell0680 OK, thanks for the update. I'm going to close this for now but please reopen if you run into this again. Thanks!!

**Closed as completed by jtriley** 2013-12-03 21:27 UTC
